### ISSUE TITLE
Crystal version

### ISSUE THREAD

**Issue by marghidanu** [PercussiveElbow/docker-crystal#1]
What version of Crystal are you using for this? The HTTP::Client from 0.35.1 doesn't support the features in the code:

```
Error: no overload matches 'HTTP::Client.new' with type UNIXSocket

Overloads are:
 - HTTP::Client.new(host : String, port = nil, tls : TLSContext = nil)
 - HTTP::Client.new(uri : URI, tls : TLSContext = nil)
 - HTTP::Client.new(uri : URI, tls : TLSContext = nil, &block)
 - HTTP::Client.new(host : String, port = nil, tls : TLSContext = nil, &block)
```

**Comment by PercussiveElbow** [comment]
I've been building this against Crystal nightly builds for some of the HTTP::Client changes under development in https://github.com/crystal-lang/crystal/issues/6011. I get the impression these will be introduced in Crystal 1.0 but that isn't confirmed yet. 

That said, this library as a whole is very unfinished right now so I wouldn't recommend using it yet unless you're fine with dealing with plenty of bugs.
